/**
 * Still version of the background, used when the animated one cannot run.
 *
 * The image is generated by the browser rather than shipped as a bitmap: two SVG turbulence
 * primitives produce fractal noise, one displaces the other, and a transfer table maps the result
 * into the same grayscale the shader uses. That keeps the fallback in the same visual language as
 * the animated background without adding a binary asset, and it renders once instead of per frame.
 *
 * It is exposed as a data URI so it can be used as a CSS background image. A background image is
 * rasterised once and then merely scaled, whereas an inline SVG element re-runs its filter on every
 * resize, which is exactly what the devices receiving this fallback cannot afford.
 */
const STILL_IMAGE_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="1000" viewBox="0 0 1600 1000">
  <defs>
    <filter id="strata" x="0" y="0" width="100%" height="100%" color-interpolation-filters="sRGB">
      <feTurbulence type="fractalNoise" baseFrequency="0.0025 0.0011" numOctaves="4" seed="11" result="warp"/>
      <feTurbulence type="fractalNoise" baseFrequency="0.0012 0.0062" numOctaves="5" seed="29" result="layers"/>
      <feDisplacementMap in="layers" in2="warp" scale="230" xChannelSelector="R" yChannelSelector="G" result="warped"/>
      <feColorMatrix in="warped" type="saturate" values="0" result="mono"/>
      <feComponentTransfer in="mono">
        <feFuncR type="table" tableValues="0.075 0.101 0.092 0.130 0.117 0.168 0.151 0.207 0.190 0.255"/>
        <feFuncG type="table" tableValues="0.075 0.101 0.092 0.130 0.117 0.168 0.151 0.207 0.190 0.255"/>
        <feFuncB type="table" tableValues="0.086 0.113 0.104 0.142 0.129 0.180 0.163 0.219 0.202 0.267"/>
        <feFuncA type="table" tableValues="1 1"/>
      </feComponentTransfer>
    </filter>
    <linearGradient id="sweep" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="#19191c" stop-opacity="0.62"/>
      <stop offset="0.55" stop-color="#19191c" stop-opacity="0.12"/>
      <stop offset="1" stop-color="#19191c" stop-opacity="0"/>
    </linearGradient>
    <radialGradient id="vignette" cx="0.5" cy="0.5" r="0.78">
      <stop offset="0.4" stop-color="#19191c" stop-opacity="0"/>
      <stop offset="1" stop-color="#19191c" stop-opacity="0.68"/>
    </radialGradient>
  </defs>
  <rect width="1600" height="1000" fill="#19191c"/>
  <rect width="1600" height="1000" filter="url(#strata)"/>
  <rect width="1600" height="1000" fill="url(#sweep)"/>
  <rect width="1600" height="1000" fill="url(#vignette)"/>
</svg>`;

/**
 * The still background as a value usable for the CSS background-image property.
 */
export const strataStillImage = `url("data:image/svg+xml,${encodeURIComponent(STILL_IMAGE_SVG)}")`;
