/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a new token pair
         * @description Consumes the presented refresh token and issues a new pair. Presenting a token that was already consumed revokes every session of the account.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and authenticate it
         * @description Creates the account, records registration metadata and returns a token pair as if the new account had logged in.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the notebooks of the authenticated account
         * @description Returns every notebook of the account, ordered by its activity timestamp descending. Pinned and unpinned notebooks are returned in one list; the pin state of each notebook is part of its representation.
         */
        get: operations["list"];
        put?: never;
        /**
         * Create a notebook
         * @description Creates an empty notebook owned by the authenticated account.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{notebookId}/sources/{sourceId}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Index a source again
         * @description Puts a source that is already stored back at the start of the indexing pipeline. A source that was read successfully before is indexed from the text that reading produced; one that was not is read again, which is what makes this the way to retry a source that failed.
         */
        post: operations["reindex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{notebookId}/sources/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a web page as a source
         * @description Stores the address and starts retrieving and indexing it. The response describes the source as it is stored, which is before the page has been read.
         */
        post: operations["addWebPage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{notebookId}/sources/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add an uploaded file as a source
         * @description Stores the file and starts indexing it. The response describes the source as it is stored, which is before indexing has finished.
         */
        post: operations["addFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{notebookId}/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the conversations of a notebook
         * @description Returns every conversation of the notebook, most recently used first, with its title and its timestamps but without its messages.
         */
        get: operations["conversations"];
        put?: never;
        /**
         * Start a conversation
         * @description Creates an empty conversation in the notebook. It has no title until the first question is asked in it.
         */
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{notebookId}/chats/{sessionId}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop an answer
         * @description Stops the answer being generated in the conversation. What was generated so far is kept, because the reader has already seen it. The response is the same whether or not an answer was running.
         */
        post: operations["stop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{notebookId}/chats/{sessionId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask a question about the sources of a notebook
         * @description Stores the question and answers it as a stream of server sent events: the sources the answer may cite, then the answer part by part, then either the finished answer or the reason none arrived. The model is the one named by the headers of the request and is addressed with the key they carry.
         */
        post: operations["ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close the current session
         * @description Revokes the refresh token of the session the presented access token belongs to.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate with credentials
         * @description Verifies the credentials, records the login and returns a token pair.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{notebookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a notebook
         * @description Returns one notebook of the account. The view of a single notebook loads it through this endpoint rather than searching the collection, so that opening it directly by its address works.
         */
        get: operations["read"];
        put?: never;
        post?: never;
        /**
         * Delete a notebook
         * @description Removes the notebook together with its sources and chat sessions. The session of the presented access token has to be open, which is verified against the database.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /**
         * Change a notebook
         * @description Changes the title, the pin state or both. An omitted field keeps its stored value.
         */
        patch: operations["update"];
        trace?: never;
    };
    "/api/v1/security/cookie-iv/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the parameters of the client side token store
         * @description Derives the key belonging to the key handle cookie of the caller and returns it together with a freshly generated initialization vector.
         */
        get: operations["parameters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{notebookId}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the sources of a notebook
         * @description Returns every source of the notebook, oldest first, each with the stage it has reached on its way into the retrieval index.
         */
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{notebookId}/chats/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a conversation
         * @description Returns the conversation with every message it holds, oldest first.
         */
        get: operations["conversation"];
        put?: never;
        post?: never;
        /**
         * Delete a conversation
         * @description Removes the conversation and its transcript. An answer being generated in it is stopped.
         */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{notebookId}/sources/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a source
         * @description Removes the source and its segments from the retrieval index. The session of the presented access token has to be open, which is verified against the database.
         */
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Refresh token to exchange for a new token pair. */
        RefreshRequest: {
            /** @description Refresh token issued by a previous login, registration or refresh. */
            refreshToken: string;
        };
        /** @description Pair of an access token and a refresh token. */
        TokenPairResponse: {
            /**
             * @description Scheme the access token is presented with.
             * @example Bearer
             */
            tokenType?: string;
            /** @description Short lived token for subsequent requests. */
            accessToken?: string;
            /**
             * Format: date-time
             * @description Expiry of the access token.
             */
            accessTokenExpiresAt?: string;
            /** @description Long lived token used to obtain a new pair. */
            refreshToken?: string;
            /**
             * Format: date-time
             * @description Expiry of the refresh token.
             */
            refreshTokenExpiresAt?: string;
        };
        /** @description Data required to create an account. */
        RegistrationRequest: {
            /**
             * @description Login name, unique across all accounts.
             * @example erik
             */
            username: string;
            /**
             * @description Given name of the user.
             * @example Erik
             */
            firstName: string;
            /**
             * @description Family name of the user.
             * @example Pfoertner
             */
            lastName: string;
            /** @description Clear text password of the new account. */
            password: string;
        };
        /** @description Account a token pair belongs to. */
        AuthenticatedUser: {
            /**
             * Format: uuid
             * @description Stable identifier of the account.
             */
            id?: string;
            /**
             * @description Login name of the account.
             * @example erik
             */
            username?: string;
            /**
             * @description Given name of the user.
             * @example Erik
             */
            firstName?: string;
            /**
             * @description Family name of the user.
             * @example Pfoertner
             */
            lastName?: string;
            /**
             * Format: date-time
             * @description Point in time the account was created.
             */
            registeredAt?: string;
            /**
             * Format: date-time
             * @description Point in time of the most recent successful login.
             */
            lastLoginAt?: string;
        };
        /** @description Issued token pair together with the account it belongs to. */
        AuthenticationResponse: {
            /** @description Issued token pair. */
            tokens?: components["schemas"]["TokenPairResponse"];
            /** @description Account the token pair belongs to. */
            user?: components["schemas"]["AuthenticatedUser"];
        };
        /** @description Data required to create a notebook. */
        NotebookCreationRequest: {
            /**
             * @description Name the notebook is created under.
             * @example Thermodynamics
             */
            title: string;
        };
        /** @description A notebook of the authenticated account. */
        NotebookResponse: {
            /**
             * Format: uuid
             * @description Stable identifier of the notebook.
             */
            id?: string;
            /**
             * @description Name the user gave the notebook.
             * @example Thermodynamics
             */
            title?: string;
            /** @description Whether the notebook is pinned to the top of the overview. */
            pinned?: boolean;
            /** @description Characters standing for the subject of the notebook, empty while unknown. */
            topicIcon?: string;
            /**
             * Format: date-time
             * @description Point in time the notebook was created.
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Point in time the notebook was last opened or changed.
             */
            lastActivityAt?: string;
            /**
             * Format: int64
             * @description Number of sources currently belonging to the notebook.
             */
            sourceCount?: number;
        };
        /** @description A source of one notebook of the authenticated account. */
        SourceResponse: {
            /**
             * Format: uuid
             * @description Stable identifier of the source.
             */
            id?: string;
            /**
             * Format: uuid
             * @description Identifier of the notebook the source belongs to.
             */
            notebookId?: string;
            /**
             * @description Name the source is listed under.
             * @example Thermodynamics.pdf
             */
            displayName?: string;
            /**
             * @description Way the source entered the notebook.
             * @enum {string}
             */
            kind?: "FILE" | "WEB";
            /** @description Name of the uploaded file or address of the page. */
            origin?: string;
            /**
             * @description Stage the source has reached on its way into the retrieval index.
             * @enum {string}
             */
            status?: "UPLOADED" | "INDEXING" | "READY" | "ERROR";
            /**
             * Format: int32
             * @description Number of tokens the indexed text was counted as, zero while unknown.
             */
            tokenCount?: number;
            /**
             * @description Reason the source could not be indexed, NONE unless it failed.
             * @enum {string}
             */
            failure?: "NONE" | "BLOCKED" | "UNREACHABLE" | "UNREADABLE" | "EMPTY" | "TOO_LARGE" | "UNEXPECTED";
            /**
             * Format: date-time
             * @description Point in time the source was added to its notebook.
             */
            createdAt?: string;
        };
        /** @description Address of a web page to add as a source. */
        WebSourceRequest: {
            /**
             * @description Address of the page to add.
             * @example https://example.org/article
             */
            url: string;
        };
        /** @description One conversation held inside a notebook, with its whole transcript. */
        ChatConversationResponse: {
            /**
             * Format: uuid
             * @description Stable identifier of the conversation.
             */
            id?: string;
            /** @description Name the conversation is listed under, empty until the first question. */
            title?: string;
            /**
             * Format: date-time
             * @description Point in time the conversation was started.
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Point in time the most recent message was exchanged.
             */
            lastMessageAt?: string;
            /** @description Messages of the conversation, oldest first. */
            messages?: components["schemas"]["ChatMessageResponse"][];
        };
        /** @description One message of the conversation held inside a notebook. */
        ChatMessageResponse: {
            /**
             * @description Author of the message.
             * @enum {string}
             */
            role?: "USER" | "ASSISTANT";
            /** @description Content of the message, in Markdown for a generated answer. */
            text?: string;
            /**
             * Format: date-time
             * @description Point in time the message was appended to the conversation.
             */
            createdAt?: string;
        };
        /** @description A question about the sources of one notebook. */
        ChatQuestionRequest: {
            /**
             * @description Question to answer from the sources of the notebook.
             * @example What does the second chapter say about entropy?
             */
            question: string;
        };
        /** @description Credentials of an existing account. */
        LoginRequest: {
            /**
             * @description Login name of the account.
             * @example erik
             */
            username: string;
            /** @description Clear text password of the account. */
            password: string;
        };
        /** @description Fields of a notebook to change. An omitted field keeps its stored value. */
        NotebookUpdateRequest: {
            /**
             * @description Name to store, omitted to keep the current one.
             * @example Thermodynamics
             */
            title?: string;
            /** @description Pin state to store, omitted to keep the current one. */
            pinned?: boolean;
        };
        /** @description Parameters for encrypting and decrypting the client side token store. */
        CookieCryptographyResponse: {
            /**
             * @description Name of the cookie the client stores its token pair in.
             * @example sumbooklm_auth
             */
            cookieName?: string;
            /**
             * @description Name of the cipher.
             * @example AES-GCM
             */
            algorithm?: string;
            /**
             * Format: int32
             * @description Length of the key in bits.
             * @example 256
             */
            keyLength?: number;
            /**
             * Format: int32
             * @description Expected length of an initialization vector in bytes.
             * @example 12
             */
            initializationVectorLength?: number;
            /**
             * Format: int32
             * @description Length of the authentication tag in bits.
             * @example 128
             */
            authenticationTagLength?: number;
            /** @description Base64 encoded key of the calling client. */
            key?: string;
            /** @description Base64 encoded vector to use for the next encryption. */
            initializationVector?: string;
        };
        /** @description One conversation held inside a notebook, without its transcript. */
        ChatSummaryResponse: {
            /**
             * Format: uuid
             * @description Stable identifier of the conversation.
             */
            id?: string;
            /** @description Name the conversation is listed under, empty until the first question. */
            title?: string;
            /**
             * Format: date-time
             * @description Point in time the conversation was started.
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Point in time the most recent message was exchanged.
             */
            lastMessageAt?: string;
            /**
             * Format: int32
             * @description Number of messages the conversation holds.
             */
            messageCount?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description A new token pair was issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description The refresh token was rejected. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationRequest"];
            };
        };
        responses: {
            /** @description The account was created and authenticated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthenticationResponse"];
                };
            };
            /** @description The request body is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The username is already taken. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The notebooks were returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotebookResponse"][];
                };
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotebookCreationRequest"];
            };
        };
        responses: {
            /** @description The notebook was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotebookResponse"];
                };
            };
            /** @description The request body is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reindex: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebookId: string;
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The source is waiting to be indexed. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SourceResponse"];
                };
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The notebook holds no such source. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addWebPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebookId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebSourceRequest"];
            };
        };
        responses: {
            /** @description The source was stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SourceResponse"];
                };
            };
            /** @description The request body is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The account owns no such notebook. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The notebook already holds this address. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebookId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description The source was stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SourceResponse"];
                };
            };
            /** @description The upload carries no bytes. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The account owns no such notebook. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The notebook already holds this content. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The upload is larger than the accepted size. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    conversations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The conversations were returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChatSummaryResponse"][];
                };
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The account owns no such notebook. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The conversation was started. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChatConversationResponse"];
                };
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The account owns no such notebook. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebookId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nothing is being generated any more. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ask: {
        parameters: {
            query?: never;
            header?: {
                "X-AI-Provider"?: string;
                "X-AI-Model"?: string;
                "X-AI-Api-Key"?: string;
                "X-AI-Base-Url"?: string;
            };
            path: {
                notebookId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatQuestionRequest"];
            };
        };
        responses: {
            /** @description The answer is being streamed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description The question or the named model is not usable. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The notebook holds no such conversation. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The account already has as many answers being generated as it may have. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session was closed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The session is already closed. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description The credentials were accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthenticationResponse"];
                };
            };
            /** @description The request body is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The credentials were rejected. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The notebook was returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotebookResponse"];
                };
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The account owns no such notebook. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The notebook was removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The session of the access token is closed. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The account owns no such notebook. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebookId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotebookUpdateRequest"];
            };
        };
        responses: {
            /** @description The notebook was changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotebookResponse"];
                };
            };
            /** @description The request body is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The account owns no such notebook. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    parameters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The parameters were derived. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CookieCryptographyResponse"];
                };
            };
            /** @description The request carries no key handle. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The sources were returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SourceResponse"][];
                };
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The account owns no such notebook. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    conversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebookId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The conversation was returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChatConversationResponse"];
                };
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The notebook holds no such conversation. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebookId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The conversation was removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The notebook holds no such conversation. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebookId: string;
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The source was removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The session of the access token is closed. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The notebook holds no such source. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
